//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamAPI.Data.Sql.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbHunger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbHunger()
        {
            this.Tamas = new HashSet<dbTama>();
        }
    
        public System.Guid hunger_id { get; set; }
        public string hunger_name { get; set; }
        public int hunger_scale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbTama> Tamas { get; set; }
    }
}
