//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamAPI.Data.Sql.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tamEntities : DbContext
    {
        public tamEntities()
            : base("name=tamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbHealth> dbHealths { get; set; }
        public virtual DbSet<dbHunger> dbHungers { get; set; }
        public virtual DbSet<dbFood> dbFoods { get; set; }
        public virtual DbSet<dbOwnerFood> dbOwnerFoods { get; set; }
        public virtual DbSet<dbOwnerSnack> dbOwnerSnacks { get; set; }
        public virtual DbSet<dbSnack> dbSnacks { get; set; }
        public virtual DbSet<dbHappiness> dbHappinesses { get; set; }
        public virtual DbSet<dbOwner> dbOwners { get; set; }
        public virtual DbSet<dbTama> dbTamas { get; set; }
    }
}
